# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77a353dc76d55ae24c006d9c3a67462c37368b281cf370dde9892909a2e37614cd1d1f5477df2e0d66602dc5bad9b36905b987f11b2c690f8c3f68b9caa4cddc

test:
  secret_key_base: 54fd5ddde368a2bcd312fcdcd547a66cedcfba635988e499bab8ab7b1ce80fe90e1b497d3d75ce28e877ce9e19488ce38e1bee2e814a27a72ee2a404fd4ec40e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
